main: com.crissuper20.lightning.LightningPlugin
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.4"
author: crissuper20
description: lnbits on minecraft
commands:
permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true