main: com.crissuper20.lightning.LightningPlugin
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: crissuper20
description: lnbits on minecraft
commands:
  lnadmin:
    description: Command for admin stuff
    usage: /<command> 
    permission: lightning.admin
  balance:
    description: Shows your Lightning balance
    usage: /<command>
    permission: lightning.balance
  pay:
    description: Pay another player over Lightning 
    usage: /<command> <bolt11>
    permission: lightning.pay
  invoice:
    description: Create an invoice, returns bolt11
    usage: /<command> <amount>
    permission: lightning.invoice
  wallet:
    description: View or create your Lightning wallet
    usage: /<command>
    permission: lightning.wallet
  splitinvoice:
    description: Create split payment invoices
    usage: /<command> [confirm]
    aliases: [splitpay]
    permission: lightning.splitinvoice
    permission-message: You don't have permission to create split invoices
permissions:
  lightning.balance:
    description: Allows using /balance
    default: true
  lightning.pay:
    description: Allows using /pay
    default: true
  lightning.invoice:
    description: Allows using /invoice
    default: true
  lightning.wallet:
    description: Allows using /wallet
    default: true
  lightning.admin:
    description: Allows using /lnadmin
    default: op
  lightning.splitinvoice:
    description: Create split payment invoices
    default: true